global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dota_fetcher'
    static_configs:
      # Use host.docker.internal to scrape the python script running on Windows host
      - targets: ['host.docker.internal:8001']
